spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/polystore
    username: poly_user
    password: poly_pass
  application:
    name: poly-store
  jpa:
    hibernate:
      ddl-auto: create-drop